@startuml
node Веб-сервер {
    database База данных
    component Веб-приложение
    interface API
}

node "Клиентский интерфейс" as Клиент

Клиент -- Веб-сервер
Веб-приложение -- API
API -- База данных

@enduml
