@startuml
package ElectronicBulletinBoard {
  class User
  class Advertisement {
    + title : String
    + description : String
    + price : Double
    + seller : User
  }
  User "1" -- "0..*" Advertisement
}
@enduml
