@startuml
left to right direction
skinparam packageStyle rectangle
actor Пользователь as User

rectangle "Электронная доска объявлений" {
  usecase "Размещение объявления" as PlaceAd
  usecase "Удаление объявления" as DeleteAd
  User --> PlaceAd
  User --> DeleteAd
}
@enduml

